FROM hexpm/elixir:1.20.3-erlang-28.1.1-debian-trixie-20260803-slim

RUN apt-get update -y && \
    apt-get install -y build-essential git inotify-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app
